In [1]:
import tensorflow as tf
import numpy as np
import time
import tensorflow.contrib.eager as tfe

In [2]:
seed = 1234
tf.random.set_random_seed(seed=seed)
np.random.seed(seed)

In [3]:
#a = np.random.randint(2, size=(3,2,2,2))
a = np.arange(24).reshape(2,3,2,2)

In [4]:
print(a)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [7]:
mean1 = np.mean(a, axis=(0,1,2))

In [8]:
print(mean1)

[11. 12.]


In [25]:
mean2 = np.mean(a, axis=(0,1,2))

In [26]:
print(mean2)

[0.25       0.33333333]


In [35]:
a1 = tf.cast(a, tf.float32)
#run the graph
with tf.Session() as sess:
    #print the random values that we sample
    print (sess.run(a1)) 

[[[[0. 0.]
   [0. 0.]]

  [[0. 1.]
   [1. 0.]]]


 [[[0. 0.]
   [1. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 0.]]

  [[0. 1.]
   [0. 1.]]]]


In [38]:
mean2 = tf.reduce_mean(a1,(0,1))

with tf.Session() as sess:
    result = sess.run(mean2)
    print(result)

[[0.33333334 0.33333334]
 [0.33333334 0.5       ]]
